version: '3.7'

services:
  sai-angular:
    image: dna/sai-angular:latest
    container_name: sai-angular
    build:
      context: ../../../
      dockerfile: angular/Dockerfile.local
    ports:
      - "4200:80"
    depends_on:
      - sai-api
    volumes:
      - ./dynamic-env.json://usr/share/nginx/html/dynamic-env.json
    networks:
      - abp-network

  sai-api:
    image: dna/sai-api:latest
    container_name: sai-api
    hostname: sai-api
    build:
      context: ../../
      dockerfile: src/Dna.Sai.HttpApi.Host/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=bbe32312-4799-4222-bbdc-665ae2e460cc
      - App__SelfUrl=https://localhost:44354
      - App__AngularUrl=http://localhost:4200
      - App_CorsOrigins=http://localhost:4200
      - App__HealthCheckUrl=http://sai-api/health-status
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=http://sai-authserver
      - App__MVCPublicUrl=https://localhost:44306
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=Sai;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    ports:
      - "44354:443"
    depends_on:
      sql-server:
        condition: service_healthy
      redis:
        condition: service_healthy  
    restart: on-failure    
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network
  
  sai-authserver:
    image: dna/sai-authserver:latest
    container_name: sai-authserver
    build:
      context: ../../
      dockerfile: src/Dna.Sai.AuthServer/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - App__SelfUrl=https://localhost:44334
      - App__CorsOrigins=http://localhost:4200,http://localhost:44307
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=https://localhost:44334/
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=bbe32312-4799-4222-bbdc-665ae2e460cc
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=Sai;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    ports:
      - "44334:443"
    depends_on:
      sql-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network

  sai-web-public:
    image: dna/sai-web-public:latest
    container_name: sai-web-public
    build:
      context: ../../
      dockerfile: src/Dna.Sai.Web.Public/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=bbe32312-4799-4222-bbdc-665ae2e460cc
      - App__SelfUrl=https://localhost:44306
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__IsContainerized=true      
      - RemoteServices__Default__BaseUrl=http://sai-api
      - AuthServer__Authority=https://localhost:44334/
      - AuthServer__MetaAddress=http://sai-authserver
      - RemoteServices__AbpAccountPublic__BaseUrl=http://sai-authserver
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=Sai;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    ports:
      - "44306:443"
    depends_on:
      sql-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network  
  db-migrator:
    image: dna/sai-db-migrator:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: src/Sai.DbMigrator/Dockerfile.local
    environment:
      - OpenIddict__Applications__Sai_App__RootUrl=http://localhost:4200
      - OpenIddict__Applications__Sai_Swagger__RootUrl=https://localhost:44354
      - OpenIddict__Applications__Sai_Web_Public_Tiered__RootUrl=https://localhost:44306
      - OpenIddict__Applications__Sai_Web_Public__RootUrl=https://localhost:44306
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=Sai;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    depends_on:
      sql-server:
        condition: service_healthy
    networks:
      - abp-network    
  
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "myPassw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - abp-network  
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S sql-server -U sa -P "myPassw0rd" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
  
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - abp-network  
    healthcheck:
      test: ["CMD", "redis-cli","ping"]      

volumes:
  sqldata:
    name: sai_sqldata
networks:
  abp-network:
    name: sai-network
    driver: bridge
